// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdk2BoUowc2FgvAwI0oDF_0fhbazoTQs',
    appId: '1:592427852800:android:2b3bdce60d524d02d1a4e5',
    messagingSenderId: '592427852800',
    projectId: 'jippymart-27c08',
    databaseURL: 'https://jippymart-27c08-default-rtdb.firebaseio.com',
    storageBucket: 'jippymart-27c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydj69AqryFDCzRSUcc5EwbGm0vXdGvsQ',
    appId: '1:592427852800:ios:7042882250c904b6d1a4e5',
    messagingSenderId: '592427852800',
    projectId: 'jippymart-27c08',
    databaseURL: 'https://jippymart-27c08-default-rtdb.firebaseio.com',
    storageBucket: 'jippymart-27c08.firebasestorage.app',
    androidClientId: '592427852800-0vu074e55r2l1v3h48qi8bkvd6u52h20.apps.googleusercontent.com',
    iosClientId: '592427852800-g5n5pd4to75i8lq6l22o37bsbq8jfir3.apps.googleusercontent.com',
    iosBundleId: 'com.foodies.customer.ios',
  );

}